[target.'cfg(all())']
rustflags = [
    # Deny `unsafe`.
    "-Dunsafe_code",
    # Clippy groups.
    "-Wclippy::pedantic",
    "-Wclippy::cargo",
    # Clippy lints.
    "-Wclippy::allow_attributes_without_reason",
    "-Wclippy::as_conversions",
    "-Wclippy::as_underscore",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::create_dir",
    "-Wclippy::dbg_macro",
    "-Wclippy::decimal_literal_representation",
    "-Wclippy::default_numeric_fallback",
    "-Wclippy::deref_by_slicing",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::filetype_is_file",
    "-Wclippy::format_push_string",
    "-Wclippy::get_unwrap",
    "-Wclippy::if_then_some_else_none",
    "-Wclippy::impl_trait_in_params",
    "-Wclippy::inline_asm_x86_att_syntax",
    "-Wclippy::large_include_file",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::missing_docs_in_private_items",
    "-Wclippy::mixed_read_write_in_expression",
    "-Wclippy::multiple_inherent_impl",
    "-Wclippy::multiple_unsafe_ops_per_block",
    "-Wclippy::mutex_atomic",
    "-Wclippy::partial_pub_fields",
    "-Wclippy::rc_mutex",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_name_method",
    "-Wclippy::self_named_module_files",
    "-Wclippy::single_char_lifetime_names",
    "-Wclippy::str_to_string",
    "-Wclippy::string_add",
    "-Wclippy::string_slice",
    "-Wclippy::string_to_string",
    "-Wclippy::suspicious_xor_used_as_pow",
    "-Wclippy::todo",
    "-Wclippy::try_err",
    "-Wclippy::undocumented_unsafe_blocks",
    "-Wclippy::unimplemented",
    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unneeded_field_pattern",
    "-Wclippy::unseparated_literal_suffix",
    "-Wclippy::verbose_file_reads",
    # Allowed Clippy lints.
    "-Aclippy::tabs_in_doc_comments",
    # Rustdoc group.
    "-Wrustdoc::all",
    # Rust groups.
    "-Wfuture_incompatible",
    "-Wrust_2018_compatibility",
    "-Wrust_2018_idioms",
    "-Wrust_2021_compatibility",
    "-Wunused",
    # Rust lints.
    "-Wdeprecated_in_future",
    "-Wmacro_use_extern_crate",
    "-Wmeta_variable_misuse",
    "-Wmissing_abi",
    "-Wmissing_copy_implementations",
    "-Wmissing_debug_implementations",
    "-Wmissing_docs",
    "-Wnon_ascii_idents",
    "-Wnoop_method_call",
    "-Wsingle_use_lifetimes",
    "-Wtrivial_casts",
    "-Wtrivial_numeric_casts",
    "-Wunreachable_pub",
    "-Wunsafe_op_in_unsafe_fn",
    "-Wunused_import_braces",
    "-Wunused_lifetimes",
    "-Wunused_qualifications",
    "-Wunused_tuple_struct_fields",
]
